### ISSUE TITLE
Development has ceased.

### ISSUE THREAD

**Issue by haneefmubarak** [kklobe/normalize#1]
@kklobe Development on a program that is actually quite useful has ceased. If you would resume, I wouldn't mind testing it and helping where I can.

**Comment by kklobe** [comment]
@haneefmubarak thanks, I created this repo from http://normalize.nongnu.org/ mosly to make sure I'd have a copy in case that page went down. I haven't done much with the code itself - are there some features you'd like to see added?

**Comment by haneefmubarak** [comment]
@kklobe thanks for replying :)

If it isn't too much, plugging into PulseAudio to automatically normalize the volume of sound that is being played might be cool. This could be done by having a running average factor to normalize by, and then increasing the running average if the past few samples were too low and decreasing it if the past few samples were too high.

**Comment by mdchaney** [comment]
Two things that would be useful:
1. There's a need to be able to handle the extended fmt chunk.  It's not difficult, and sox in particular will create an extended chunk when the sample size is above 16 bits.  I just made this change in my "waveform" source:

https://github.com/mdchaney/waveform

The audio format is set to 65534/-2 (depending on signed/unsigned) and the chunk length is 40.  The audio format then exists in an extended field, with the same value of "1" for PCM.  This also includes a "valid bits per sample" field.  Please see my source at around line 1690, it's pretty simple.

Of course, I haven't looked to see if normalize can handle larger sample sizes, and if not that would be a welcomed addition.
1. It would be nice to handle AIFs, which are very similar to WAVs.

I deal with audio and we're now seeing sample size going to 24 and 32 bit, along with sample rates going to 48k and even 96k.  I actually have an entire catalog here that was mastered at 24-bit, 96k stereo.  The files are huge.  But relative to disk storage they're still smaller than mp3s were 15 years ago.

Anyway, normalize is a useful tool even though I haven't used it yet.
